stages:
- name: build
  steps:
  - runScriptConfig:
      image: registry-vpc.cn-hangzhou.aliyuncs.com/geeme/node:latest
      shellScript: |-
        alias cnpm="npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc"X
        cnpm install
        npm run build--${CICD_GIT_BRANCH}
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: geeme/hairdressing-frontend-${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment_${CICD_GIT_BRANCH}.yaml
branch:
  include:
    - master
    - develop
    - release
    - hotfix
