kind: Service
apiVersion: v1
metadata:
  name: gms-web-${CICD_GIT_BRANCH}-service
  namespace: ${CICD_GIT_BRANCH}
spec:
  selector:
    app: gms-web-${CICD_GIT_BRANCH}
  ports:
    - name: gms-web-${CICD_GIT_BRANCH}-service-port
      protocol: TCP
      port: 8080
      targetPort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gms-web-${CICD_GIT_BRANCH}
  namespace: ${CICD_GIT_BRANCH}
  labels:
    app: gms-web-${CICD_GIT_BRANCH}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gms-web-${CICD_GIT_BRANCH}
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gms-web-${CICD_GIT_BRANCH}
    spec:
      imagePullSecrets:
      - name: registry-cn-hangzhou-aliyuncs-com
      containers:
      - name: gms-web-${CICD_GIT_BRANCH}
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: NODE_ENV
            value: ${CICD_GIT_BRANCH}

