stages:
- name: build
  steps:
  - runScriptConfig:
      image: registry-vpc.cn-hangzhou.aliyuncs.com/geeme/node:latest
      shellScript: |-
        #echo 192.30.253.112 github.com >> /etc/hosts
        alias cnpm="npm --registry=https://registry.npm.taobao.org --cache=$HOME/.npm/.cache/cnpm --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc"
        #npm install -g cnpm --registry=https://registry.npm.taobao.org
        #cnpm install
        wget http://geeme-release.oss-cn-hangzhou-internal.aliyuncs.com/package-list/hairdressing_frontend-${CICD_GIT_BRANCH}.tar.gz
        tar zxf hairdressing_frontend-${CICD_GIT_BRANCH}.tar.gz
        #npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver
        #npm config delete registry
        #npm config delete disturl
        #npm install --ignore-scripts
        #npm install
        npm run build--${CICD_GIT_BRANCH}
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: geeme/hairdressing-frontend-${CICD_GIT_BRANCH}:${CICD_GIT_COMMIT}
      pushRemote: true
      registry: registry.cn-hangzhou.aliyuncs.com
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
- name: Deploy
  steps:
  - runScriptConfig:
      image: registry.cn-hangzhou.aliyuncs.com/geeme/kubectl:latest
      shellScript: |-
        environment_key=`curl -s http://gather.gateway.geeme.cn/environment_key`
        echo $environment_key
        if [[ ${CICD_GIT_BRANCH} == release ]];then sed -i "s/namespace: \\${CICD_GIT_BRANCH}/namespace: ${CICD_GIT_BRANCH}-${environment_key}/g" deployment_${CICD_GIT_BRANCH}.yaml; fi
        sed -i "s/\\${CICD_GIT_BRANCH}/${CICD_GIT_BRANCH}/g" deployment_${CICD_GIT_BRANCH}.yaml
        sed -i "s/\\${CICD_IMAGE}/${CICD_IMAGE}/g" deployment_${CICD_GIT_BRANCH}.yaml
        sed -i "s/\\${CICD_GIT_COMMIT}/${CICD_GIT_COMMIT}/g" deployment_${CICD_GIT_BRANCH}.yaml
        cat deployment_${CICD_GIT_BRANCH}.yaml
        if [[ ${CICD_GIT_BRANCH} == release ]];then context=; else context="--kubeconfig=/root/.kube/config-qa"; fi
        kubectl ${context} apply -f ./deployment_${CICD_GIT_BRANCH}.yaml
        curl -s http://geeme-release.oss-cn-hangzhou-internal.aliyuncs.com/package-list/alterpod.sh -o alterpod.sh && sh alterpod.sh $environment_key
    env:
      CICD_IMAGE: registry.cn-hangzhou.aliyuncs.com\\/geeme\\/hairdressing-frontend-${CICD_GIT_BRANCH}
branch:
  include:
    - master
    - develop
    - release
    - hotfix
